# Generated by Django 5.0.2 on 2024-02-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Videos', '0003_alter_category_options_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like_type',
        ),
    ]
