# Generated by Django 5.0.2 on 2024-02-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Videos', '0005_remove_video_video_url_video_video_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['updated_at', 'created_at', 'title']},
        ),
    ]
